# Generated by Django 5.2.8 on 2025-11-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="base.topic"
            ),
        ),
    ]
